### PR TITLE
Automatic removal of orphan nodes

### PR DESCRIPTION
**Pull request by roysc**
Completes work from https://github.com/celestiaorg/smt/pull/24 :
* [x]  implement the actual removing of orphans
* [x]  more extensive testing (update/delete operations, tree with multiple entries)

### CODE REVIEW

**Comment by musalbas** [comment]
Thanks for continuing this work and this PR!

Changing the leaf value (https://github.com/celestiaorg/smt/pull/36/commits/341c9985ac9bf4b32561c6f9ba94f71c545789af) seems to a breaking change. Is this necessary to implementing orphan removal, and why? There already shouldn't be any ambiguity about which key a leaf is for, as it's already prefixed in the leaf's value.

**Comment by roysc** [comment]
@musalbas sorry, my commit message wasn't very clear. The problem only arises when deleting a leaf with a duplicate value - there's no way to know if a value is still referenced by another leaf. Another solution would be some kind of reference count.

**Comment by adlerjohn** [comment]
@roysc The implementation storing the hash of the value for the leaf value is an implementation detail. It's in no way required. You could instead store values in the separate map `hash(key) -> value`, as in https://github.com/celestiaorg/smt/issues/14#issuecomment-762895582. Breaking the commitment specification is simply not a viable workaround to an implementation detail.

I suggest you start by refactoring as per #14, then pruning will follow readily.

**Comment by roysc** [comment]
@adlerjohn my apologies for not respecting the commitment spec. Using `key -> value` is a simple change; but if this mapping is stored in the same DB, would there be any concern about malicious users intentionally storing a plain key that collides with an existing tree hash? Or are you suggesting using a separate DB instance for this?

And could you clarify what you mean by modifying the current test suite? Are you referring only to the changes in the commitment spec, or changes in the LazyLedger/Celestia core? I haven't modified any existing tests here.

**Comment by adlerjohn** [comment]
> Or are you suggesting using a separate DB instance for this?

Yes, the suggestion is a separate KV store just for values. There's no inherent reason to put both values and nodes in the map KV store.

> And could you clarify what you mean by modifying the current test suite? Are you referring only to the changes in the commitment spec

Yes, to clarify I mean that the commitment as specified [here](https://github.com/celestiaorg/celestia-specs/blob/65d4d528beafaf8d84f7eb805db940f05f2a2c93/src/specs/data_structures.md#sparse-merkle-tree) must be the same before and after any PR dealing with implementation details.

**Comment by roysc** [comment]
I'm not able to reopen this PR, new one: https://github.com/celestiaorg/smt/pull/37

**Pull request closed without merging**
