### PR TITLE
Automatic removal of orphan nodes

### PR DESCRIPTION
**Pull request by tzdybal**
Work in progress.

TODO:
  - [x] `AutoOrphanRemoval` option (false by default)
  - [x] configuration mechanism ~(`With(opt Option)`?)~ (variadic arguments in constructor)
  - [x] simple test
  - [ ] implement the actual removing of orphans
  - [ ] more extensive testing (update/delete operations, tree with multiple entries)

### CODE REVIEW

**Comment by musalbas** [comment]
Closing, as superseded by #36 and #37.

**Comment by liamsi** [comment]
As mentioned in the opening comments of #37, the PR there is build on top of the changes here. Hence that PR is against this branch (and not against main/master): 
image

**Comment by liamsi** [comment]
Now that #37 was merged in here. Can we actually resolve the merge conflicts, mark this as ready for review, give it a 2nd pass and finally merge it?

**Comment by adlerjohn** [comment]
This should be fully superseded by #37 unless I'm mistaken, so it can be closed @liamsi

**Comment by liamsi** [comment]
> This should be fully superseded by #37 unless I'm mistaken, so it can be closed @liamsi

No, #37 builds on the changes here. Hence the changes of #37 were merged into this branch / PR in 763105b

**Comment by liamsi** [comment]
Resolved the merge conflicts. Happy to help push this over the finish line if necessary!

**Comment by adlerjohn** [comment]
The only difference between the head from #37 and this PR is in `smt.go` unless I'm mistaken.

```sh
diff celestiaorg/smt/smt.go roysc/smt/smt.go
```

The diff:

```diff
305,308d304
< 	// The offset from the bottom of the tree to the start of the side nodes.
< 	// Note: i-offsetOfSideNodes is the index into sideNodes[]
< 	offsetOfSideNodes := smt.depth() - len(sideNodes)
< 
312c308,312
< 		if i-offsetOfSideNodes < 0 || sideNodes[i-offsetOfSideNodes] == nil {
---
> 		// The offset from the bottom of the tree to the start of the side nodes
> 		// i-offsetOfSideNodes is the index into sideNodes[]
> 		offsetOfSideNodes := smt.depth() - len(sideNodes)
> 
> 		if i-offsetOfSideNodes < 0 {
```

Moving the offset calculation is from https://github.com/celestiaorg/smt/pull/35, so nothing to see there. The only thing of interest is that #37 removes the condition `sideNodes[i-offsetOfSideNodes] == nil`. That condition should never be hit, since none of the `sideNodes` will be `nil`, so shouldn't be a problem to remove. All tests pass in #37, so looks like it's indeed not needed.

**Review by adlerjohn — APPROVED** [review]

**Review by liamsi — APPROVED** [review]
Thanks @adlerjohn 👍🏼

**Pull request merged**
