### PR TITLE
Create CHANGELOG.md, CHANGELOG-PENDING.md, and corresponding GH action

### LINKED ISSUE #65: Automated CHANGELOG.md check for smt
There should be an automated step that ensures that a CHANGELOG.md file is appropriately updated for all merges to the main branch.

There should be a proper description in an issue and corresponding PR as well as a summary in the CHANGELOG.md file. This will be enforced through an automated action. In rare cases for small PRs it may be acceptable to skip this.

### PR DESCRIPTION
**Pull request by jbowen93**
Create CHANGELOG.md and CHANGELOG-PENDING.md files and a corresponding "Pending Changelog Checker" action that runs on all PRs to the master branch.

This check will only pass if the CHANGELOG-PENDING.md file is updated in the PR.

This check can be bypassed by labeling the PR with no_changelog

Resolves #65

### CODE REVIEW

**Review by liamsi — APPROVED** [review]
LGTM, but I'd like to have @musalbas' approval here as well as he is the main author of this repo.

**Comment by musalbas** [comment]
What's the rationale of this?

**Review by adlerjohn — APPROVED** [review]

**Comment by liamsi** [comment]
> What's the rationale of this?

In order to have a changelog moving forward, this actiion checks that on each PR the pending changlog is updated. Unless it is flagged the label `no_changelog`. That ensures that PRs will be accompanied with a changelog entry and that the developer thinks about categorizing the PR properly. This ensure a minimal viable changelog. Ideally, on each release the maintainer does not just simply copy over the the list from pending into the actual changelog but also summarizes the changes properly. But everything is better than not having a changelog at all.

**Comment by musalbas** [comment]
This feels like extra unnecessary bureaucracy and loop-jumping, when I thought the whole point of git squash merging is to have a clean changelog. However, I won't veto merging this.

**Comment by adlerjohn** [comment]
> the whole point of git squash merging is to have a clean changelog

I think that's orthogonal? Squash and merge gives a clean git commit history, yes, but that's not a changelog. This PR adds a CI workflow to automatically produce a changelog between release versions, consumable by an end user.

**Comment by musalbas** [comment]
Git commits should be changelog entries. What else are they for, then? The standard practice in most projects I've seen, including Linux, Bitcoin, and Ubuntu packages, is to use the git commit history as the changelog.

**Comment by liamsi** [comment]
> This PR adds a CI workflow to automatically produce a changelog between release versions, consumable by an end user.

Not really, this PR does what it say in the opening comment, it adds a checker that:

> This check will only pass if the CHANGELOG-PENDING.md file is updated in the PR.

> Git commits should be changelog entries.

Sure, I don't mind this here. But I still think it's worth thinking ahead/deciding on each merge if this change was a breaking one, if it adds a new feature, fixes a bug etc. and have that reflected in the changelog instead of just a list of commits.

**Comment by jbowen93** [comment]
FYI someone else has to merge this.

**Pull request merged**
